- src/main/java/pro/laplacelab/mt4j/exception/InvalidInputException.java
- src/main/java/pro/laplacelab/mt4j/model/Input.java
- src/test/java/pro/laplacelab/mt4j/model/AdvisorTest.java
- src/test/java/pro/laplacelab/mt4j/service/AdvisorServiceImplTest.java
UnitTest for Input constructor. Fixes #71
> UnitTest for Input constructor. Fixes #71

- src/main/java/pro/laplacelab/mt4j/model/Advisor.java
- src/main/java/pro/laplacelab/mt4j/model/Position.java
- src/test/java/pro/laplacelab/mt4j/BaseTestPreparation.java
- src/test/java/pro/laplacelab/mt4j/model/AdvisorTest.java
- src/test/java/pro/laplacelab/mt4j/model/PositionTest.java
- src/test/java/pro/laplacelab/mt4j/service/PositionServiceImplTest.java
Add openPrice, closePrice, commission to Position model. Fixes #73
> Add openPrice, closePrice, commission to Position model. Fixes #73

- mql5client/Include/Network/ApiService.mqh
- mql5client/Include/Network/RestClient.mqh
- mql5client/Include/Transaction/SignalExecutor.mqh
Support parsing Signal array (ClientSide). Fixes #60
> Support parsing Signal array (ClientSide). Fixes #60

- mql5client/Include/Common/Utils.mqh
- mql5client/Include/Provider/PositionProvider.mqh
Impl conversion of StopLoss and TakeProfit in Utils. Fixes  #47
> Impl conversion of StopLoss and TakeProfit in Utils. Fixes  #47

- README.md
- mql5client/Include/Common/Enums.mqh
- src/main/java/pro/laplacelab/mt4j/enums/SignalType.java
- src/main/java/pro/laplacelab/mt4j/example/Example.java
- src/main/java/pro/laplacelab/mt4j/model/Signal.java
- src/test/java/pro/laplacelab/mt4j/model/SignalTest.java
- src/test/java/pro/laplacelab/mt4j/service/SignalServiceImplTest.java
Get rid from NO_ACTION signal type. Fixes #80
> Get rid from NO_ACTION signal type. Fixes #80

- mql5client/Include/Common/Utils.mqh
- mql5client/Include/Transaction/SignalExecutor.mqh
Impl update position. Fixes #86
> Impl update position. Fixes #86

- mql5client/mt4j.mq5
> Design mt4j.mq5. Fixes #81

- mql5client/Include/Network/ApiService.mqh
- mql5client/Include/Provider/AccountProvider.mqh
- mql5client/Include/Provider/InputsProvider.mqh
- mql5client/mt4j.mq5
Fix memory leaks in mt4j.mq5 Fixes #91
> Fix memory leaks in mt4j.mq5 Fixes #91

- README.md
- mql5client/Include/Common/Enums.mqh
Update README.md exchange protocol description. Fixes #79
> Update README.md exchange protocol description. Fixes #79

- mql5client/Include/Network/ApiService.mqh
- mql5client/Include/Provider/AccountProvider.mqh
- mql5client/Include/Provider/PositionProvider.mqh
Inject mql dependencies with ApplicationContext. Fixes #99
> Inject mql dependencies with ApplicationContext. Fixes #99

- mql5client/Include/AppllicationContext/AppllicationContext.mqh
- mql5client/Include/Common/Enums.mqh
- mql5client/Include/Network/ApiService.mqh
- mql5client/Include/Network/RequestFactory.mqh
- mql5client/Include/Network/RestClient.mqh
- mql5client/Include/Provider/AccountProvider.mqh
- mql5client/Include/Provider/InputsProvider.mqh
- mql5client/Include/Provider/MarketProvider.mqh
- mql5client/Include/Provider/PositionProvider.mqh
- mql5client/Include/Transaction/SignalExecutor.mqh
Cast all class fields to one style. Fixes #93
> Cast all class fields to one style. Fixes #93

- README.md
Add install instruction to README. Fixes #107
> Add install instruction to README. Fixes #107

- mt5/Library/AppllicationContext/AppllicationContext.mqh
- mt5/MT4J.mq5
Sync ApplicationContext and MT4J.mt5 Fixes #109
> Sync ApplicationContext and MT4J.mt5 Fixes #109

- mt5/Library/ApplicationContext/ApplicationContext.mqh
- mt5/Library/Common/Utils.mqh
- mt5/Library/Network/ApiService.mqh
- mt5/Library/Network/RequestFactory.mqh
- mt5/Library/Network/RestClient.mqh
- mt5/Library/Provider/AccountProvider.mqh
- mt5/Library/Provider/InputsProvider.mqh
- mt5/Library/Provider/MarketProvider.mqh
- mt5/Library/Provider/PositionProvider.mqh
- mt5/Library/Transaction/SignalExecutor.mqh
- mt5/MT4J.mq5
Mql compile error in master. Fixes #97
> Mql compile error in master. Fixes #97

- mt5/Library/Network/RestClient.mqh
- mt5/Library/Provider/MarketProvider.mqh
- src/main/java/pro/laplacelab/mt4j/model/Rate.java
- src/test/java/pro/laplacelab/mt4j/JsonMapper.java
- src/test/java/pro/laplacelab/mt4j/controller/SignalControllerTest.java
Convert seconds to LocalDateTime with Jackson in Rate model. Fixes #112
> Convert seconds to LocalDateTime with Jackson in Rate model. Fixes #112

- mt5/Library/Common/Enums.mqh
- mt5/Library/Common/Structures.mqh
- mt5/Library/Network/ApiService.mqh
- mt5/Library/Transaction/SignalExecutor.mqh
Separate constructor definitions and impls. Fixes #116
> Separate constructor definitions and impls. Fixes #116

- README.md
> Refactor README Fixes #124

- mt5/Library/Provider/InputsProvider.mqh
- src/main/java/pro/laplacelab/mt4j/enums/InputType.java
- src/main/java/pro/laplacelab/mt4j/model/Input.java
- src/test/java/pro/laplacelab/mt4j/model/AdvisorTest.java
- src/test/java/pro/laplacelab/mt4j/service/AdvisorServiceImplTest.java
Support boolean type advisor inputs. Fixes #120
> Support boolean type advisor inputs. Fixes #120

- mt5/Library/ApplicationContext/ApplicationContext.mqh
- mt5/Library/Transaction/SignalExecutor.mqh
Remove Infinity loops in SignalExecutor. Fixes #117
> Remove Infinity loops in SignalExecutor. Fixes #117

- mt5/Library/ApplicationContext/ApplicationContext.mqh
- mt5/Library/Provider/MarketProvider.mqh
Make RatesBufferSize as advisor input. Fixes #128
> Make RatesBufferSize as advisor input. Fixes #128

- mt5/Library/ApplicationContext/ApplicationContext.mqh
- mt5/Library/Network/RestClient.mqh
Inputs for struct RestConfig. Fixes #123
> Inputs for struct RestConfig. Fixes #123

- mt5/Library/Network/ApiService.mqh
- mt5/Library/Network/RequestFactory.mqh
- mt5/Library/Network/RestClient.mqh
- mt5/Library/Provider/AccountProvider.mqh
- mt5/Library/Provider/InputsProvider.mqh
- mt5/Library/Provider/MarketProvider.mqh
- mt5/Library/Provider/PositionProvider.mqh
- mt5/Library/Transaction/SignalExecutor.mqh
Detach constructor definition and implementation. Fixes #133
> Detach constructor definition and implementation. Fixes #133

- src/main/java/pro/laplacelab/mt4j/StrategyCondition.java
- src/main/java/pro/laplacelab/mt4j/example/Example.java
Create Condition interface for define sub strategy. Fixes #119
> Create Condition interface for define sub strategy. Fixes #119

- src/main/java/pro/laplacelab/mt4j/mapper/BarSeriesMapper.java
- src/main/java/pro/laplacelab/mt4j/mapper/BarSeriesMapperImpl.java
- src/test/java/pro/laplacelab/mt4j/mapper/BarSeriesMapperImplTest.java
Converter from Rate to ta4j relevant object. Fixes #122
> Converter from Rate to ta4j relevant object. Fixes #122

- src/main/java/pro/laplacelab/mt4j/Strategy.java
- src/main/java/pro/laplacelab/mt4j/StrategyCondition.java
- src/main/java/pro/laplacelab/mt4j/strategy/Example.java
- src/test/java/pro/laplacelab/mt4j/service/SignalServiceImplTest.java
Apply rates mapping. Fixes #140
> Apply rates mapping. Fixes #140

- src/main/java/pro/laplacelab/mt4j/StrategyCondition.java
- src/main/java/pro/laplacelab/mt4j/adapter/ta4j/TAdapter.java
- src/main/java/pro/laplacelab/mt4j/adapter/ta4j/TBar.java
- src/main/java/pro/laplacelab/mt4j/strategy/Example.java
- src/test/java/pro/laplacelab/mt4j/adapter/TAdapterTest.java
> Spread field. Fixes #139

- src/main/java/pro/laplacelab/mt4j/adapter/ta4j/TBar.java
- src/test/java/pro/laplacelab/mt4j/adapter/TAdapterTest.java
> UTest for TBar. Fixes #147

- src/main/java/pro/laplacelab/mt4j/adapter/ta4j/TAdapter.java
- src/main/java/pro/laplacelab/mt4j/adapter/ta4j/TBar.java
- src/main/java/pro/laplacelab/mt4j/adapter/ta4j/TBarBuilder.java
- src/test/java/pro/laplacelab/mt4j/adapter/TAdapterTest.java
> Add TBarBuilder

- src/main/java/pro/laplacelab/mt4j/adapter/ta4j/Spreadable.java
- src/main/java/pro/laplacelab/mt4j/adapter/ta4j/TBar.java
- src/main/java/pro/laplacelab/mt4j/adapter/ta4j/TBarBuilder.java
- src/main/java/pro/laplacelab/mt4j/adapter/ta4j/TBarComparator.java
- src/test/java/pro/laplacelab/mt4j/adapter/TAdapterTest.java
- src/test/java/pro/laplacelab/mt4j/adapter/ta4j/TBarComparatorTest.java
Make TBar Comparable. Fixes #151
> Make TBar Comparable. Fixes #151

- src/main/java/pro/laplacelab/mt4j/model/Input.java
- src/main/java/pro/laplacelab/mt4j/model/Position.java
- src/main/java/pro/laplacelab/mt4j/model/Rate.java
- src/main/java/pro/laplacelab/mt4j/model/Signal.java
Get rid from redundant lombok annotations. Fixes #126
> Get rid from redundant lombok annotations. Fixes #126

- pom.xml
- src/main/java/pro/laplacelab/mt4j/exception/DuplicateAdvisorException.java
- src/main/java/pro/laplacelab/mt4j/service/AdvisorServiceImpl.java
- src/main/java/pro/laplacelab/mt4j/service/PositionService.java
- src/test/java/pro/laplacelab/mt4j/adapter/TAdapterTest.java
- src/test/java/pro/laplacelab/mt4j/service/AdvisorServiceImplTest.java
Verify duplicate MagicNumber. Fixes #121
> Verify duplicate MagicNumber. Fixes #121

- src/main/java/pro/laplacelab/mt4j/service/PositionService.java
- src/test/java/pro/laplacelab/mt4j/service/PositionServiceImplTest.java
UTest for PositionService. Fixes #155
> UTest for PositionService. Fixes #155

- src/main/java/pro/laplacelab/mt4j/model/Market.java
- src/main/java/pro/laplacelab/mt4j/service/AdvisorService.java
- src/main/java/pro/laplacelab/mt4j/service/AdvisorServiceImpl.java
- src/main/java/pro/laplacelab/mt4j/service/PositionServiceImpl.java
- src/main/java/pro/laplacelab/mt4j/service/SignalServiceImpl.java
- src/test/java/pro/laplacelab/mt4j/adapter/TAdapterTest.java
- src/test/java/pro/laplacelab/mt4j/adapter/ta4j/TBarComparatorTest.java
- src/test/java/pro/laplacelab/mt4j/controller/AdvisorControllerTest.java
- src/test/java/pro/laplacelab/mt4j/controller/SignalControllerTest.java
- src/test/java/pro/laplacelab/mt4j/model/AdvisorTest.java
- src/test/java/pro/laplacelab/mt4j/model/PositionTest.java
- src/test/java/pro/laplacelab/mt4j/model/SignalTest.java
- src/test/java/pro/laplacelab/mt4j/service/AdvisorServiceImplTest.java
- src/test/java/pro/laplacelab/mt4j/service/PositionServiceImplTest.java
- src/test/java/pro/laplacelab/mt4j/service/SignalServiceImplTest.java
- src/test/java/pro/laplacelab/mt4j/service/StrategyServiceImplTest.java
Annotate all test with DisplayName. Fixes #158
> Annotate all test with DisplayName. Fixes #158

- README.md
> Update README. Fixes #160

- mt5/Library/Network/ApiService.mqh
- mt5/Library/Network/RequestFactory.mqh
- mt5/Library/Network/RestClient.mqh
- mt5/Library/Provider/InputsProvider.mqh
- mt5/Library/Provider/MarketProvider.mqh
- mt5/Library/Provider/PositionProvider.mqh
- mt5/Library/Transaction/SignalExecutor.mqh
Refactor client method signature. Fixes #166
> Refactor client method signature. Fixes #166

- src/main/resources/application-dev.properties
Create develop git branch. Fixes #168
> Create develop git branch. Fixes #168

- mt5/Library/Network/ApiService.mqh
- mt5/Library/Network/RestClient.mqh
- mt5/Library/Provider/PositionProvider.mqh
- mt5/Library/Transaction/SignalExecutor.mqh
Compile errors in master. Fixes #170
> Compile errors in master. Fixes #170

- lombok.config
- pom.xml
Exclude lombok from test coverage. Fixes #173
> Exclude lombok from test coverage. Fixes #173

- .github/workflows/build.yml
Exclude strategy package from code coverage. Fixes #176
> Exclude strategy package from code coverage. Fixes #176

- src/test/java/pro/laplacelab/mt4j/ApplicationTest.java
> Test main class. Fixes #177

- .github/workflows/build.yml
> Build failed. Fixes #182

- mt5/Library/Provider/PositionProvider.mqh
Get signals request parse error. Fixes #186
> Get signals request parse error. Fixes #186

- mt5/Library/Provider/MarketProvider.mqh
- mt5/Library/Provider/PositionProvider.mqh
Fetch history not filtering by magic number. Fixes #187
> Fetch history not filtering by magic number. Fixes #187

- mt5/Library/Provider/MarketProvider.mqh
Fetch open price incorrectly. Fixes #190
> Fetch open price incorrect. Fixes #190

- mt5/Library/Provider/MarketProvider.mqh
- mt5/Library/Provider/PositionProvider.mqh
Fetch open price incorrectly. Fixes #190
> Fetch open price incorrectly. Fixes #190

- mt5/Library/ApplicationContext/ApplicationContext.mqh
- mt5/Library/Network/ExceptionInterceptor.mqh
- mt5/Library/Network/RestClient.mqh
- src/main/java/pro/laplacelab/mt4j/validation/AdvisorExceptionHandlerController.java
- src/main/java/pro/laplacelab/mt4j/validation/ExceptionResponse.java
Exception interceptor. Fixes #185
> Exception interceptor. Fixes #185

- lombok.config
- src/main/java/pro/laplacelab/mt4j/validation/ExceptionResponse.java
- src/test/java/pro/laplacelab/mt4j/JsonMapper.java
- src/test/java/pro/laplacelab/mt4j/adapter/TAdapterTest.java
- src/test/java/pro/laplacelab/mt4j/adapter/ta4j/TBarComparatorTest.java
- src/test/java/pro/laplacelab/mt4j/controller/AdvisorControllerTest.java
- src/test/java/pro/laplacelab/mt4j/model/AdvisorTest.java
- src/test/java/pro/laplacelab/mt4j/model/PositionTest.java
- src/test/java/pro/laplacelab/mt4j/model/SignalTest.java
- src/test/java/pro/laplacelab/mt4j/service/AdvisorServiceImplTest.java
- src/test/java/pro/laplacelab/mt4j/service/PositionServiceImplTest.java
- src/test/java/pro/laplacelab/mt4j/service/SignalServiceImplTest.java
- src/test/java/pro/laplacelab/mt4j/service/StrategyServiceImplTest.java
UTest for AdvisorExceptionHandlerController. Fixes #197
> UTest for AdvisorExceptionHandlerController. Fixes #197

- mt5/Library/Network/RestClient.mqh
Remove old error handling. Fixes #201
> Remove old error handling. Fixes #201

- mt5/Library/Network/ApiService.mqh
- mt5/Library/Network/ExceptionInterceptor.mqh
- mt5/Library/Network/RequestFactory.mqh
- mt5/Library/Network/RestClient.mqh
- mt5/Library/Provider/AccountProvider.mqh
- mt5/Library/Provider/InputsProvider.mqh
- mt5/Library/Provider/MarketProvider.mqh
- mt5/Library/Provider/PositionProvider.mqh
- mt5/Library/Transaction/SignalExecutor.mqh
Separate empty constructors. Fixes #204
> Separate empty constructors. Fixes #204
